#!/bin/bash
hostname=$(hostname -s)
user=$(whoami)
cmd=$(cp -rf /home/module/modules.conf /etc/modules-load.d/modules.conf)
cmd=$(chmod 777 /etc/modules-load.d/modules.conf)
cmd=$(modprobe overlay)
cmd=$(modprobe br_netfilter)
cmd=$(cp -rf /home/module/k8s.conf /etc/sysctl.d/k8s.conf)
cmd=$(chmod 411 /etc/sysctl.d/k8s.conf)
cmd=$(sudo sysctl --system)
cmd=$(apt-get update)
cmd=$(apt-get install -y ca-certificates curl gnupg lsb-release)
cmd=$(apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates)
cmd=$(curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -)
cmd=$(add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable")
cmd=$(apt-get update)
cmd=$(apt-get install -y containerd.io docker-ce docker-ce-cli)
cmd=$(mkdir -p /etc/systemd/system/docker.service.d)
cmd=$(cp -rf /home/module/daemon.json /etc/docker/daemon.json)
cmd=$(chmod 411 /etc/docker/daemon.json)
cmd=$(systemctl daemon-reload)
cmd=$(systemctl restart docker)
cmd=$(systemctl enable docker)
cmd=$(apt-get update)
cmd=$(apt-get install -y git wget curl)
cmd=$(VER=$(curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest|grep tag_name | cut -d '"' -f 4|sed 's/v//g'))
cmd=$(wget https://github.com/Mirantis/cri-dockerd/releases/download/v${VER}/cri-dockerd-${VER}.amd64.tgz)
cmd=$(tar xvf cri-dockerd-${VER}.amd64.tgz)
cmd=$(mv cri-dockerd/cri-dockerd /usr/local/bin/)
cmd=$(wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service)
cmd=$(wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket)
cmd=$(mv cri-docker.socket cri-docker.service /etc/systemd/system/)
cmd=$(sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service)
cmd=$(systemctl daemon-reload)
cmd=$(systemctl enable cri-docker.service)
cmd=$(systemctl enable --now cri-docker.socket)